name: Release

on:
  release:
    types: [created]

jobs:
  contract-release:
    name: Contract File Release
    runs-on: [ self-hosted, linux ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 
