name: Release

on:
  release:
    types: [created]

jobs:
  contract-release:
    name: Contract File Release
    runs-on: ubuntu-linux
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          components: clippy, rustfmt

      - name: Generate Latest Schema Files
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --example schema

      - name: Generate Rust Docs
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --no-deps

      - name: Stage Cargo Docs
        run: |
          # Add redirect page to inner doc index
          echo "<meta http-equiv=\"refresh\" content=\"0; url=funding_trading_bridge_smart_contract\">" >> ./target/doc/index.html
          # Create doc deployment location
          mkdir ./pages-files
          # Move documentation to its configured location in settings
          cp -r target/doc ./pages-files/docs

      - name: Deploy Docs to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          folder: pages-files

      - name: Optimize Contract
        run: make optimize

      - name: Release Contract Files
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            artifacts/funding_trading_bridge_smart_contract.wasm
            artifacts/checksums.txt
            schema/*.json
